name: MLB Daily Î”xR Bot

on:
  schedule:
    - cron: "*/5 * * * *"
    # 14:30 UTC daily (adjust if needed)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install required packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
         packages: |
            dplyr
            baseballr
            ggplot2
            httr
            jsonlite
            readr
            stringr

      - name: Run MLB Bot Script
        run: Rscript R/script.r
        env:
          apikey: ${{ secrets.apikey }}
          apikeysecret: ${{ secrets.apikeysecret }}
          accesstoken: ${{ secrets.accesstoken }}
          accesstokensecret: ${{ secrets.accesstokensecret }}
