name: Run MLB Project Script

on:
  workflow_dispatch:

jobs:
  run-mlb-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev libpng-dev libtiff5-dev libjpeg-dev libwebp-dev libx11-dev libxext-dev libxtst-dev libxrender-dev libssl-dev libxml2-dev libgit2-dev libglpk-dev libgmp-dev libgsl-dev

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("dplyr", "ggplot2", "httr", "jsonlite", "readr", "stringr", "tidyverse"), repos="https://cran.rstudio.com")'
          Rscript -e 'if (!requireNamespace("pak", quietly = TRUE)) install.packages("pak", repos="https://cran.rstudio.com"); pak::pak("BillPetti/baseballr")'

      - name: Run MLB Script
        run: Rscript R/script.r
        env:
          apikey: ${{ secrets.apikey }}
          apikeysecret: ${{ secrets.apikeysecret }}
          accesstoken: ${{ secrets.accesstoken }}
          accesstokensecret: ${{ secrets.accesstokensecret }}